# Урок
# >, <, >=, <=, !=, ==
# print(10 > "20")
# print(10 >= True)
# print(10 < 20.1)
# print(10 <= 20)
# print(10 == 20)
# print(10 != 20)
# a = "oto-to".lower()
# print(a)
# a = "oto-to".upper()
# print(a)
# a = "oto-to".capitalize()
# print(a)
# a = "oto-to dfs fsd!a".title()
# print(a)
# b = "oto-To"

# print(a > b)
# print(a == b)
# print(a >= b)
# print(ord("!"))
# print("ozod" >= "kto-to")
# print("ozod" == "kto-to")
# print("ozod" != "kto-to")
# print("ozod" < "kto-to")
# print("ozod" <= "kto-to")
# print("a" > "f")

# text_1 = input("Введи первый текст чтоб сравнить: ")
# text_2 = input("Введи второй текст чтоб сравнить: ")
# if text_1 > text_2 and text_1.startswith("a"): print("ok")
# elif text_1 == text_2 or not text_1.startswith("a"): print("типа ок")
# else: print("NOT OK")
# print(not True)
# print(not False)
# print("ХАНА ТЕБЕ! ЭТО ВИРУС!!!")
# input()